site_name: BME AUT Mikroszolgáltatások és konténeralapú szoftverfejlesztés
site_author: Dudás Ákos
copyright: Copyright &copy; BME VIK AUT
repo_name: bmeviauav42/jegyzetek
repo_url: https://github.com/bmeviauav42/jegyzetek

theme:
  name: material
  custom_dir: theme-overrides
  language: hu
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb
        name: Világos téma
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb-outline
        name: Sötét téma
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
  logo: logo-bme-aut.png
  favicon: favicon.ico

extra_css:
  - extra-material-theme.css

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - index.md
  - hazi-feladat.md
  - Docker:
      - Docker/Docker-alapok.md
      - Docker/Dockerfile-compose.md
  - Architektúra:
      - Architektura/AdatbazisApiGateway.md
      - Architektura/Kommunikacio.md
  - DevOps:
      - DevOps/Nyomkovetes.md
      - DevOps/Logging-Health-Checks.md
      - DevOps/Prometheus-monitoring.md
  - Kubernetes:
      - Kubernetes/Kubernetes-alapok.md
      - Kubernetes/Kubernetes-alkalmazas-telepites.md
      - AKS/aks.md
  - Serverless:
      - Serverless/serverless.md
